apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ocp46-_infraid_
  managedFields:
  - apiVersion: machine.openshift.io/v1beta1
  name: ocp46-worker
  namespace: openshift-machine-api
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp46-_infraid_
      machine.openshift.io/cluster-api-machineset: ocp46-worker
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp46-_infraid_
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ocp46-worker
    spec:
      metadata: {}
      providerSpec:
        value:
          apiVersion: vsphereprovider.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: 120
          kind: VSphereMachineProviderSpec
          memoryMiB: 8192
          metadata:
            creationTimestamp: null
          network:
            devices:
            - networkName: "VM Network"
          numCPUs: 2
          numCoresPerSocket: 1
          snapshot: ""
          template: rhcos-4.6.1
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: ktzdc
            datastore: nvme500
            folder: /ktzdc/vm/awesomo/redhat/ocp46
            resourcePool: /ktzdc/host/ktzcluster/Resources
            server: 192.168.1.240
status:
  observedGeneration: 1
  replicas: 0
